### ISSUE TITLE
I cannot use the functions expand and collapse

### ISSUE THREAD

**Issue by andersonlazcano** [dkhlystov/jquery-treegrid#10]
I have tried the following code:

First I already make the table with all items collapsed, this work well.
$('#table').treegrid();

Then, i want to have a button to expand all and/or collapse all. But i didn't work. 
Code:

 $('#table').treegrid('expand');
 $('#table').treegrid('collapse');
     
Thank you for your time.
I'm using the following version:
/*
 * TreeGrid plugin v0.1.5
 * Copyright 2016 Dmitry Khlystov
 * Licensed under the MIT license
 */

**Comment by dkhlystov** [comment]
Post a HTML of the table

**Comment by dkhlystov** [comment]
Note, that you should use expand/collapse functions on table row

**Comment by dkhlystov** [comment]
See https://github.com/dkhlystov/jquery-treegrid/issues/8  about expand all/collapse all

**Comment by krosoftware** [comment]
you can see example here: 
https://github.com/dkhlystov/jquery-treegrid/issues/8
