### ISSUE TITLE
jQuery 3.2 issue: Cannot create property 'guid' on string 

### ISSUE THREAD

**Issue by wcg777** [dkhlystov/jquery-treegrid#6]
While upgraded to jQuery 3.2, I got an error: Uncaught TypeError: Cannot create property 'guid' on string '.doc-delete'

```
if ( !handler.guid ) {
			handler.guid = jQuery.guid++;
		}
```

please test it. thanks.

**Comment by dkhlystov** [comment]
In which file this error is occur?

**Comment by wcg777** [comment]
Other plugin caused this error. my fault, please delete this issue.
