### ISSUE TITLE
How to change width and height of expanded/collapsed icon?

### ISSUE THREAD

**Issue by krosoftware** [dkhlystov/jquery-treegrid#7]
Hello
I try to make bigger expanded/collapsed icon but can not figure out how to do that.
If I use default width/height style, icon is not centered on both cases. For example, I can perfect size it on collapsed state but when expanded, it is not positioned on the middle and vice-versa.
Thank you for your ideas.

**Comment by dkhlystov** [comment]
Hello!
Attach preview image and/or code you write.

**Comment by krosoftware** [comment]
Hello
I changed this in css:

.treegrid-expander::after {
    border: 12px solid transparent;
    margin-left: -18px;
}

and it looks like this:
https://imgur.com/hRoUQAp

when I change margin-top: -14px; to align it horizontally, then it looks like this:
https://imgur.com/crkpSXt

What I need is just to make expanded and contracted icon bigger (but also aligned horizontal and vertical in middle) so it can be used on mobile. OR, I can also put fontawesome chevron fonts (but I don't know how...)
Thank you.

**Comment by krosoftware** [comment]
How to make bigger expand/collapse icons, please? Or, how to put some normal icons so it can be used on mobile? Currently, it is too small. Thank you.

**Comment by dkhlystov** [comment]
You can use `treegrid-expander-expanded` class to set additional style of expended icon, like this
```
.treegrid-expander.treegrid-expander-expanded:after {
    margin-top: youwant;
}
```
Or you can use font awesome icons with sets a some styles:
```
.treegrid-expander {
    font-family: "Font Awesome 5 Pro"; // or set your font-awesome font
}
.treegrid-expander:after {
    content: "\f0da"; // right
}
.treegrid-expander.treegrid-expander-expanded:after {
    content: "\f793"; // down
}
```

**Comment by krosoftware** [comment]
Hello
thank you so much, I finally solved it and it looks like this:

```
.treegrid-expander {
  margin-right:14px;
	display: inline-block;
	margin-left: -30px;
	position: relative;
	width: 24px;
}
.treegrid-expander {
	vertical-align: middle;
}
.treegrid-expander-expanded,
.treegrid-expander-collapsed {
	cursor: pointer;
}

.treegrid-expander-collapsed {
}
.treegrid-expander {
    font-family: "Font Awesome 5 Pro";
}
.treegrid-expander::after {
    content: " ";
}
.treegrid-expander.treegrid-expander-expanded::after {
  content: "\f078";
  font-size:22px;
  margin-left:14px;
}
.treegrid-expander.treegrid-expander-collapsed::after {
  content: "\f054";
  font-size:22px;
  margin-left:14px;  
}

```
Thank you.
